openapi: 3.0.1
info:
  title: Betting Odds Middleware API
  description: API to get betting odds from various betting sites.
  version: 1.0.1
servers:
  - url: https://api.your-middleware.com
    description: Main URL of the middleware
paths:
  /sports/getSports:
    get:
      summary: Get sports list
      description: Returns all available sports.
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: List of all available sports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sport'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /sports/getEvents:
    get:
      summary: Get events list
      description: Returns all available events.
      parameters:
        - in: query
          name: sportKey
          required: true
          schema:
            type: string
            example: "basketball_nba"
          description: The sport key of the event
        - in: query
          name: regions
          required: false
          schema:
            type: string
            default: "eu,uk"
            example: "eu"
          description: Comma-separated list of regions to get odds for (e.g., "us,uk,eu")
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: List of all available events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /odds/head2head:
    get:
      summary: Get head-to-head odds
      description: Returns the top 'X' head-to-head odds for a specific event.
      parameters:
        - in: query
          name: eventId
          required: true
          schema:
            type: string
            example: "bda33adca828c09dc3cac3a856aef176"
          description: ID of the event
        - in: query
          name: sportKey
          required: true
          schema:
            type: string
            example: "basketball_nba"
          description: The sport key of the event
        - in: query
          name: regions
          required: false
          schema:
            type: string
            default: "eu,uk"
            example: "eu"
          description: Comma-separated list of regions to get odds for (e.g., "us,uk,eu")
        - in: query
          name: records
          required: false
          schema:
            type: number
            default: 1
            example: 3
          description: Number of records to retrieve
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: List of the top 'X' head-to-head odds
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Odds'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.
  
  /odds/spreads:
    get:
      summary: Get head-to-head handicap odds
      description: Returns the top 'X' head-to-head handicap odds for a specific event.
      parameters:
        - in: query
          name: eventId
          required: true
          schema:
            type: string
            example: "bda33adca828c09dc3cac3a856aef176"
          description: ID of the event
        - in: query
          name: sportKey
          required: true
          schema:
            type: string
            example: "basketball_nba"
          description: The sport key of the event
        - in: query
          name: regions
          required: false
          schema:
            type: string
            default: "eu,uk"
            example: "eu"
          description: Comma-separated list of regions to get odds for (e.g., "us,uk,eu")
        - in: query
          name: records
          required: false
          schema:
            type: number
            default: 1
            example: 3
          description: Number of records to retrieve
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: List of the top 'X' head-to-head handicap odds
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Odds'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          description: A unique 32 character identifier for the event.
          example: e912304de2b2ce35b473ce2ecd3d1502
        sport_key:
          type: string
          description: A unique slug for the sport. Use this as the "sport" param in /odds requests.
          example: americanfootball_nfl
        sport_title:
          type: string
          description: A presentable title of the sport. Occasionally this value can change, for example if a league undergoes a name change or change in sponsorship.
          example: NFL
        commence_time:
          type: string
          format: date-time
          description: The match start time (ISO 8601 formatted). This will be a Unix timestamp integer if the dateFormat query param is set to dateFormat=unix.
          example: 2023-10-11T23:10:00Z
        home_team:
          type: string
          description: The home team. If home/away is not applicable for the sport (such as MMA and Tennis), it will be one of the participants. Null for outrights (futures) events.
          example: Houston Texans
          nullable: true
        away_team:
          type: string
          description: The away team. If home/away is not applicable for the sport (such as MMA and Tennis), it will be one of the participants. Null for outrights (futures) events.
          example: Kansas City Chiefs
          nullable: true
    
    Sport:
      type: object
      properties:
        key:
          type: string
          description: A unique slug for the sport. Use this as the "sport" param in /odds requests.
          example: americanfootball_nfl
        active:
          type: boolean
          description: Indicates if the sport is in season.
          example: true
        group:
          type: string
          description: A broader grouping.
          example: American Football
        description:
          type: string
          description: A brief description of the sport. Subject to change (for example, if sponsors change).
          example: US Football
        title:
          type: string
          description: A presentable title of the sport. Occasionally this value can change, for example if a league undergoes a name change or change in sponsorship.
          example: NFL
        has_outrights:
          type: boolean
          description: Indicates if the sport has outrights markets.
          example: false

    Bookmaker:
      type: object
      properties:
        url:
          type: string
          description: The URL of the bookmaker's website.
          example: https://www.draftkings.com
        key:
          type: string
          description: A unique slug (key) of the bookmaker.
          example: draftkings
        title:
          type: string
          description: A formatted title of the bookmaker.
          example: DraftKings
        last_update:
          type: string
          format: date-time
          description: A timestamp of when the bookmaker's odds were last read. Will be an integer if dateFormat=unix, otherwise it will be a string.
          example: 2023-10-10T12:10:29Z
        markets:
          type: array
          items:
            $ref: '#/components/schemas/Market'

    Market:
      type: object
      properties:
        key:
          type: string
          description: The name of the odds market.
          example: h2h
          enum:
            - h2h
            - spreads
            - totals
            - outrights
        last_update:
          type: string
          format: date-time
          description: A timestamp of when the market's odds were last read. Will be an integer if dateFormat=unix, otherwise it will be a string. To check the recency of odds, we recommend using this field instead of the "last_update" field at the bookmaker level.
          example: 2023-10-10T12:10:29Z
        outcomes:
          type: array
          items:
            $ref: '#/components/schemas/Outcome'

    Outcome:
      type: object
      properties:
        name:
          type: string
          description: The outcome label. The value will depend on the market. For totals markets, this will be 'Over' or 'Under'. For team markets, it will be the name of the team or participant, or 'Draw'.
          example: Houston Texans
        price:
          type: number
          format: float
          description: The odds of the outcome. The format is determined by the oddsFormat query param. The format is decimal by default.
          example: 2.23
        point:
          type: number
          nullable: true
          description: The handicap or points of the outcome, only applicable to spreads and totals markets (this property will be missing for h2h and outrights markets).
          example: 20.5
        description:
          type: string
          nullable: true
          description: This field is only relevant for certain markets. It contains more information about the outcome (for example, for player prop markets, it includes the player's name).

    Odds:
      type: object
      properties:
        event:
          $ref: '#/components/schemas/Event'
        bookmakers:
          type: array
          items:
            $ref: '#/components/schemas/Bookmaker'

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: [ ]
