/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.betapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

@SpringBootApplication
public class BetApi {

    public static void main(String[] args) {
		SpringApplication springApp = new SpringApplication(BetApi.class);
		springApp.run(args);
    }

}
