/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.betapi;

import org.junit.Test;
import static org.junit.Assert.*;

public class BetApiTest {
    @Test public void appHasAGreeting() {
        BetApi classUnderTest = new BetApi();
    }
}
