/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package betapi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class BetApi {

    public static void main(String[] args) {
		SpringApplication springApp = new SpringApplication(BetApi.class);
		springApp.run(args);
    }

}
