export interface Vector {
  fg_pct_H:number,
  fg3_pct_H:number,
  ft_pct_H:number,
  reb_H:number,
  tot_ast_H:number,
  tot_tov_H:number,
  tot_stl_H:number,
  tot_blk_H:number,
  ts_pct_H:number,
  w_pct_H:number,
  w_pct_last_5_games_H:number,
  fg_pct_A:number,
  fg3_pct_A:number,
  ft_pct_A:number,
  reb_A:number,
  tot_ast_A:number,
  tot_tov_A:number,
  tot_stl_A:number,
  tot_blk_A:number,
  ts_pct_A:number,
  w_pct_A:number,
  w_pct_last_5_games_A:number,
  off_rating_H:number,
  def_rating_H:number,
  off_rating_A:number,
  def_rating_A:number,
  lineup_efficiency_H:number,
  lineup_efficiency_A:number,
  home_team: string,
  away_team: string,
  game_id: string,
  winner: string,
  pts_H: number,
  pts_A: number,
  season: string,
  date: string,
  playoff: boolean,
  referee_name: string,
  referee_id: number,
}
