# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.global_stats import GlobalStats  # noqa: F401,E501
from swagger_server.models.stat import Stat  # noqa: F401,E501
from swagger_server import util


class ActualMatchStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, global_stats: GlobalStats=None, by_home_stats: Stat=None, by_away_stats: Stat=None):  # noqa: E501
        """ActualMatchStats - a model defined in Swagger

        :param global_stats: The global_stats of this ActualMatchStats.  # noqa: E501
        :type global_stats: GlobalStats
        :param by_home_stats: The by_home_stats of this ActualMatchStats.  # noqa: E501
        :type by_home_stats: Stat
        :param by_away_stats: The by_away_stats of this ActualMatchStats.  # noqa: E501
        :type by_away_stats: Stat
        """
        self.swagger_types = {
            'global_stats': GlobalStats,
            'by_home_stats': Stat,
            'by_away_stats': Stat
        }

        self.attribute_map = {
            'global_stats': 'global_stats',
            'by_home_stats': 'by_home_stats',
            'by_away_stats': 'by_away_stats'
        }
        self._global_stats = global_stats
        self._by_home_stats = by_home_stats
        self._by_away_stats = by_away_stats

    @classmethod
    def from_dict(cls, dikt) -> 'ActualMatchStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ActualMatchStats of this ActualMatchStats.  # noqa: E501
        :rtype: ActualMatchStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def global_stats(self) -> GlobalStats:
        """Gets the global_stats of this ActualMatchStats.


        :return: The global_stats of this ActualMatchStats.
        :rtype: GlobalStats
        """
        return self._global_stats

    @global_stats.setter
    def global_stats(self, global_stats: GlobalStats):
        """Sets the global_stats of this ActualMatchStats.


        :param global_stats: The global_stats of this ActualMatchStats.
        :type global_stats: GlobalStats
        """

        self._global_stats = global_stats

    @property
    def by_home_stats(self) -> Stat:
        """Gets the by_home_stats of this ActualMatchStats.


        :return: The by_home_stats of this ActualMatchStats.
        :rtype: Stat
        """
        return self._by_home_stats

    @by_home_stats.setter
    def by_home_stats(self, by_home_stats: Stat):
        """Sets the by_home_stats of this ActualMatchStats.


        :param by_home_stats: The by_home_stats of this ActualMatchStats.
        :type by_home_stats: Stat
        """

        self._by_home_stats = by_home_stats

    @property
    def by_away_stats(self) -> Stat:
        """Gets the by_away_stats of this ActualMatchStats.


        :return: The by_away_stats of this ActualMatchStats.
        :rtype: Stat
        """
        return self._by_away_stats

    @by_away_stats.setter
    def by_away_stats(self, by_away_stats: Stat):
        """Sets the by_away_stats of this ActualMatchStats.


        :param by_away_stats: The by_away_stats of this ActualMatchStats.
        :type by_away_stats: Stat
        """

        self._by_away_stats = by_away_stats
