# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.average import Average  # noqa: F401,E501
from swagger_server import util


class AveragePlayer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plus_minus: float=None):  # noqa: E501
        """AveragePlayer - a model defined in Swagger

        :param plus_minus: The plus_minus of this AveragePlayer.  # noqa: E501
        :type plus_minus: float
        """
        self.swagger_types = {
            'plus_minus': float
        }

        self.attribute_map = {
            'plus_minus': 'plus_minus'
        }
        self._plus_minus = plus_minus

    @classmethod
    def from_dict(cls, dikt) -> 'AveragePlayer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AveragePlayer of this AveragePlayer.  # noqa: E501
        :rtype: AveragePlayer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plus_minus(self) -> float:
        """Gets the plus_minus of this AveragePlayer.


        :return: The plus_minus of this AveragePlayer.
        :rtype: float
        """
        return self._plus_minus

    @plus_minus.setter
    def plus_minus(self, plus_minus: float):
        """Sets the plus_minus of this AveragePlayer.


        :param plus_minus: The plus_minus of this AveragePlayer.
        :type plus_minus: float
        """

        self._plus_minus = plus_minus
