# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.global_stats import GlobalStats  # noqa: F401,E501
from swagger_server.models.stat import Stat  # noqa: F401,E501
from swagger_server import util


class LastMatchStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, global_stats: List[GlobalStats]=None, by_home_stats: List[Stat]=None, by_away_stats: List[Stat]=None):  # noqa: E501
        """LastMatchStats - a model defined in Swagger

        :param global_stats: The global_stats of this LastMatchStats.  # noqa: E501
        :type global_stats: List[GlobalStats]
        :param by_home_stats: The by_home_stats of this LastMatchStats.  # noqa: E501
        :type by_home_stats: List[Stat]
        :param by_away_stats: The by_away_stats of this LastMatchStats.  # noqa: E501
        :type by_away_stats: List[Stat]
        """
        self.swagger_types = {
            'global_stats': List[GlobalStats],
            'by_home_stats': List[Stat],
            'by_away_stats': List[Stat]
        }

        self.attribute_map = {
            'global_stats': 'global_stats',
            'by_home_stats': 'by_home_stats',
            'by_away_stats': 'by_away_stats'
        }
        self._global_stats = global_stats
        self._by_home_stats = by_home_stats
        self._by_away_stats = by_away_stats

    @classmethod
    def from_dict(cls, dikt) -> 'LastMatchStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LastMatchStats of this LastMatchStats.  # noqa: E501
        :rtype: LastMatchStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def global_stats(self) -> List[GlobalStats]:
        """Gets the global_stats of this LastMatchStats.


        :return: The global_stats of this LastMatchStats.
        :rtype: List[GlobalStats]
        """
        return self._global_stats

    @global_stats.setter
    def global_stats(self, global_stats: List[GlobalStats]):
        """Sets the global_stats of this LastMatchStats.


        :param global_stats: The global_stats of this LastMatchStats.
        :type global_stats: List[GlobalStats]
        """

        self._global_stats = global_stats

    @property
    def by_home_stats(self) -> List[Stat]:
        """Gets the by_home_stats of this LastMatchStats.


        :return: The by_home_stats of this LastMatchStats.
        :rtype: List[Stat]
        """
        return self._by_home_stats

    @by_home_stats.setter
    def by_home_stats(self, by_home_stats: List[Stat]):
        """Sets the by_home_stats of this LastMatchStats.


        :param by_home_stats: The by_home_stats of this LastMatchStats.
        :type by_home_stats: List[Stat]
        """

        self._by_home_stats = by_home_stats

    @property
    def by_away_stats(self) -> List[Stat]:
        """Gets the by_away_stats of this LastMatchStats.


        :return: The by_away_stats of this LastMatchStats.
        :rtype: List[Stat]
        """
        return self._by_away_stats

    @by_away_stats.setter
    def by_away_stats(self, by_away_stats: List[Stat]):
        """Sets the by_away_stats of this LastMatchStats.


        :param by_away_stats: The by_away_stats of this LastMatchStats.
        :type by_away_stats: List[Stat]
        """

        self._by_away_stats = by_away_stats
