# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.actual_match_stats import ActualMatchStats  # noqa: F401,E501
from swagger_server.models.last_match_stats import LastMatchStats  # noqa: F401,E501
from swagger_server import util


class MatchStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, actual_match_stats: List[ActualMatchStats]=None, last_match_stats: List[LastMatchStats]=None):  # noqa: E501
        """MatchStats - a model defined in Swagger

        :param actual_match_stats: The actual_match_stats of this MatchStats.  # noqa: E501
        :type actual_match_stats: List[ActualMatchStats]
        :param last_match_stats: The last_match_stats of this MatchStats.  # noqa: E501
        :type last_match_stats: List[LastMatchStats]
        """
        self.swagger_types = {
            'actual_match_stats': List[ActualMatchStats],
            'last_match_stats': List[LastMatchStats]
        }

        self.attribute_map = {
            'actual_match_stats': 'actual_match_stats',
            'last_match_stats': 'last_match_stats'
        }
        self._actual_match_stats = actual_match_stats
        self._last_match_stats = last_match_stats

    @classmethod
    def from_dict(cls, dikt) -> 'MatchStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchStats of this MatchStats.  # noqa: E501
        :rtype: MatchStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def actual_match_stats(self) -> List[ActualMatchStats]:
        """Gets the actual_match_stats of this MatchStats.


        :return: The actual_match_stats of this MatchStats.
        :rtype: List[ActualMatchStats]
        """
        return self._actual_match_stats

    @actual_match_stats.setter
    def actual_match_stats(self, actual_match_stats: List[ActualMatchStats]):
        """Sets the actual_match_stats of this MatchStats.


        :param actual_match_stats: The actual_match_stats of this MatchStats.
        :type actual_match_stats: List[ActualMatchStats]
        """

        self._actual_match_stats = actual_match_stats

    @property
    def last_match_stats(self) -> List[LastMatchStats]:
        """Gets the last_match_stats of this MatchStats.


        :return: The last_match_stats of this MatchStats.
        :rtype: List[LastMatchStats]
        """
        return self._last_match_stats

    @last_match_stats.setter
    def last_match_stats(self, last_match_stats: List[LastMatchStats]):
        """Sets the last_match_stats of this MatchStats.


        :param last_match_stats: The last_match_stats of this MatchStats.
        :type last_match_stats: List[LastMatchStats]
        """

        self._last_match_stats = last_match_stats
