# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlayerStatsPlayerEfficiency(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, all: float=None, filtered_matches: float=None):  # noqa: E501
        """PlayerStatsPlayerEfficiency - a model defined in Swagger

        :param all: The all of this PlayerStatsPlayerEfficiency.  # noqa: E501
        :type all: float
        :param filtered_matches: The filtered_matches of this PlayerStatsPlayerEfficiency.  # noqa: E501
        :type filtered_matches: float
        """
        self.swagger_types = {
            'all': float,
            'filtered_matches': float
        }

        self.attribute_map = {
            'all': 'all',
            'filtered_matches': 'filtered_matches'
        }
        self._all = all
        self._filtered_matches = filtered_matches

    @classmethod
    def from_dict(cls, dikt) -> 'PlayerStatsPlayerEfficiency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlayerStats_player_efficiency of this PlayerStatsPlayerEfficiency.  # noqa: E501
        :rtype: PlayerStatsPlayerEfficiency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def all(self) -> float:
        """Gets the all of this PlayerStatsPlayerEfficiency.


        :return: The all of this PlayerStatsPlayerEfficiency.
        :rtype: float
        """
        return self._all

    @all.setter
    def all(self, all: float):
        """Sets the all of this PlayerStatsPlayerEfficiency.


        :param all: The all of this PlayerStatsPlayerEfficiency.
        :type all: float
        """

        self._all = all

    @property
    def filtered_matches(self) -> float:
        """Gets the filtered_matches of this PlayerStatsPlayerEfficiency.


        :return: The filtered_matches of this PlayerStatsPlayerEfficiency.
        :rtype: float
        """
        return self._filtered_matches

    @filtered_matches.setter
    def filtered_matches(self, filtered_matches: float):
        """Sets the filtered_matches of this PlayerStatsPlayerEfficiency.


        :param filtered_matches: The filtered_matches of this PlayerStatsPlayerEfficiency.
        :type filtered_matches: float
        """

        self._filtered_matches = filtered_matches
