# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.player_advanced_details_statistics import PlayerAdvancedDetailsStatistics  # noqa: F401,E501
from swagger_server import util


class PlayerAdvancedDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, statistics: PlayerAdvancedDetailsStatistics=None):  # noqa: E501
        """PlayerAdvancedDetails - a model defined in Swagger

        :param statistics: The statistics of this PlayerAdvancedDetails.  # noqa: E501
        :type statistics: PlayerAdvancedDetailsStatistics
        """
        self.swagger_types = {
            'statistics': PlayerAdvancedDetailsStatistics
        }

        self.attribute_map = {
            'statistics': 'statistics'
        }
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'PlayerAdvancedDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlayerAdvancedDetails of this PlayerAdvancedDetails.  # noqa: E501
        :rtype: PlayerAdvancedDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def statistics(self) -> PlayerAdvancedDetailsStatistics:
        """Gets the statistics of this PlayerAdvancedDetails.


        :return: The statistics of this PlayerAdvancedDetails.
        :rtype: PlayerAdvancedDetailsStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: PlayerAdvancedDetailsStatistics):
        """Sets the statistics of this PlayerAdvancedDetails.


        :param statistics: The statistics of this PlayerAdvancedDetails.
        :type statistics: PlayerAdvancedDetailsStatistics
        """

        self._statistics = statistics
