# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TeamBase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, ticker: str=None, logo: str=None):  # noqa: E501
        """TeamBase - a model defined in Swagger

        :param id: The id of this TeamBase.  # noqa: E501
        :type id: int
        :param name: The name of this TeamBase.  # noqa: E501
        :type name: str
        :param ticker: The ticker of this TeamBase.  # noqa: E501
        :type ticker: str
        :param logo: The logo of this TeamBase.  # noqa: E501
        :type logo: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'ticker': str,
            'logo': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'ticker': 'ticker',
            'logo': 'logo'
        }
        self._id = id
        self._name = name
        self._ticker = ticker
        self._logo = logo

    @classmethod
    def from_dict(cls, dikt) -> 'TeamBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TeamBase of this TeamBase.  # noqa: E501
        :rtype: TeamBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this TeamBase.


        :return: The id of this TeamBase.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this TeamBase.


        :param id: The id of this TeamBase.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this TeamBase.


        :return: The name of this TeamBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TeamBase.


        :param name: The name of this TeamBase.
        :type name: str
        """

        self._name = name

    @property
    def ticker(self) -> str:
        """Gets the ticker of this TeamBase.


        :return: The ticker of this TeamBase.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker: str):
        """Sets the ticker of this TeamBase.


        :param ticker: The ticker of this TeamBase.
        :type ticker: str
        """

        self._ticker = ticker

    @property
    def logo(self) -> str:
        """Gets the logo of this TeamBase.


        :return: The logo of this TeamBase.
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo: str):
        """Sets the logo of this TeamBase.


        :param logo: The logo of this TeamBase.
        :type logo: str
        """

        self._logo = logo
