# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.team_advanced_detailed_statistics_statistics import TeamAdvancedDetailedStatisticsStatistics  # noqa: F401,E501
from swagger_server import util


class TeamAdvancedDetailedStatistics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, statistics: TeamAdvancedDetailedStatisticsStatistics=None):  # noqa: E501
        """TeamAdvancedDetailedStatistics - a model defined in Swagger

        :param statistics: The statistics of this TeamAdvancedDetailedStatistics.  # noqa: E501
        :type statistics: TeamAdvancedDetailedStatisticsStatistics
        """
        self.swagger_types = {
            'statistics': TeamAdvancedDetailedStatisticsStatistics
        }

        self.attribute_map = {
            'statistics': 'statistics'
        }
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'TeamAdvancedDetailedStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TeamAdvancedDetailedStatistics of this TeamAdvancedDetailedStatistics.  # noqa: E501
        :rtype: TeamAdvancedDetailedStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def statistics(self) -> TeamAdvancedDetailedStatisticsStatistics:
        """Gets the statistics of this TeamAdvancedDetailedStatistics.


        :return: The statistics of this TeamAdvancedDetailedStatistics.
        :rtype: TeamAdvancedDetailedStatisticsStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: TeamAdvancedDetailedStatisticsStatistics):
        """Sets the statistics of this TeamAdvancedDetailedStatistics.


        :param statistics: The statistics of this TeamAdvancedDetailedStatistics.
        :type statistics: TeamAdvancedDetailedStatisticsStatistics
        """

        self._statistics = statistics
