# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.player import Player  # noqa: F401,E501
from swagger_server.models.team_info import TeamInfo  # noqa: F401,E501
from swagger_server import util


class Team(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, team_ticker: str=None, team_info: TeamInfo=None, team_players: List[Player]=None):  # noqa: E501
        """Team - a model defined in Swagger

        :param team_ticker: The team_ticker of this Team.  # noqa: E501
        :type team_ticker: str
        :param team_info: The team_info of this Team.  # noqa: E501
        :type team_info: TeamInfo
        :param team_players: The team_players of this Team.  # noqa: E501
        :type team_players: List[Player]
        """
        self.swagger_types = {
            'team_ticker': str,
            'team_info': TeamInfo,
            'team_players': List[Player]
        }

        self.attribute_map = {
            'team_ticker': 'team_ticker',
            'team_info': 'team_info',
            'team_players': 'team_players'
        }
        self._team_ticker = team_ticker
        self._team_info = team_info
        self._team_players = team_players

    @classmethod
    def from_dict(cls, dikt) -> 'Team':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Team of this Team.  # noqa: E501
        :rtype: Team
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team_ticker(self) -> str:
        """Gets the team_ticker of this Team.


        :return: The team_ticker of this Team.
        :rtype: str
        """
        return self._team_ticker

    @team_ticker.setter
    def team_ticker(self, team_ticker: str):
        """Sets the team_ticker of this Team.


        :param team_ticker: The team_ticker of this Team.
        :type team_ticker: str
        """

        self._team_ticker = team_ticker

    @property
    def team_info(self) -> TeamInfo:
        """Gets the team_info of this Team.


        :return: The team_info of this Team.
        :rtype: TeamInfo
        """
        return self._team_info

    @team_info.setter
    def team_info(self, team_info: TeamInfo):
        """Sets the team_info of this Team.


        :param team_info: The team_info of this Team.
        :type team_info: TeamInfo
        """

        self._team_info = team_info

    @property
    def team_players(self) -> List[Player]:
        """Gets the team_players of this Team.


        :return: The team_players of this Team.
        :rtype: List[Player]
        """
        return self._team_players

    @team_players.setter
    def team_players(self, team_players: List[Player]):
        """Sets the team_players of this Team.


        :param team_players: The team_players of this Team.
        :type team_players: List[Player]
        """

        self._team_players = team_players
