# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.advanced_match_details import AdvancedMatchDetails  # noqa: F401,E501
from swagger_server.models.team_advanced_details_points import TeamAdvancedDetailsPoints  # noqa: F401,E501
from swagger_server.models.team_advanced_details_recent_record import TeamAdvancedDetailsRecentRecord  # noqa: F401,E501
from swagger_server import util


class TeamAdvancedDetails(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, recent_record: TeamAdvancedDetailsRecentRecord=None, points: TeamAdvancedDetailsPoints=None, recent_matches: List[AdvancedMatchDetails]=None):  # noqa: E501
        """TeamAdvancedDetails - a model defined in Swagger

        :param recent_record: The recent_record of this TeamAdvancedDetails.  # noqa: E501
        :type recent_record: TeamAdvancedDetailsRecentRecord
        :param points: The points of this TeamAdvancedDetails.  # noqa: E501
        :type points: TeamAdvancedDetailsPoints
        :param recent_matches: The recent_matches of this TeamAdvancedDetails.  # noqa: E501
        :type recent_matches: List[AdvancedMatchDetails]
        """
        self.swagger_types = {
            'recent_record': TeamAdvancedDetailsRecentRecord,
            'points': TeamAdvancedDetailsPoints,
            'recent_matches': List[AdvancedMatchDetails]
        }

        self.attribute_map = {
            'recent_record': 'recent_record',
            'points': 'points',
            'recent_matches': 'recent_matches'
        }
        self._recent_record = recent_record
        self._points = points
        self._recent_matches = recent_matches

    @classmethod
    def from_dict(cls, dikt) -> 'TeamAdvancedDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TeamAdvancedDetails of this TeamAdvancedDetails.  # noqa: E501
        :rtype: TeamAdvancedDetails
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recent_record(self) -> TeamAdvancedDetailsRecentRecord:
        """Gets the recent_record of this TeamAdvancedDetails.


        :return: The recent_record of this TeamAdvancedDetails.
        :rtype: TeamAdvancedDetailsRecentRecord
        """
        return self._recent_record

    @recent_record.setter
    def recent_record(self, recent_record: TeamAdvancedDetailsRecentRecord):
        """Sets the recent_record of this TeamAdvancedDetails.


        :param recent_record: The recent_record of this TeamAdvancedDetails.
        :type recent_record: TeamAdvancedDetailsRecentRecord
        """

        self._recent_record = recent_record

    @property
    def points(self) -> TeamAdvancedDetailsPoints:
        """Gets the points of this TeamAdvancedDetails.


        :return: The points of this TeamAdvancedDetails.
        :rtype: TeamAdvancedDetailsPoints
        """
        return self._points

    @points.setter
    def points(self, points: TeamAdvancedDetailsPoints):
        """Sets the points of this TeamAdvancedDetails.


        :param points: The points of this TeamAdvancedDetails.
        :type points: TeamAdvancedDetailsPoints
        """

        self._points = points

    @property
    def recent_matches(self) -> List[AdvancedMatchDetails]:
        """Gets the recent_matches of this TeamAdvancedDetails.


        :return: The recent_matches of this TeamAdvancedDetails.
        :rtype: List[AdvancedMatchDetails]
        """
        return self._recent_matches

    @recent_matches.setter
    def recent_matches(self, recent_matches: List[AdvancedMatchDetails]):
        """Sets the recent_matches of this TeamAdvancedDetails.


        :param recent_matches: The recent_matches of this TeamAdvancedDetails.
        :type recent_matches: List[AdvancedMatchDetails]
        """

        self._recent_matches = recent_matches
