openapi: 3.0.1
info:
  title: NBA Middleware API
  description: Bridge to expose nba_api library through HTTP api
  version: 1.0.0
servers:
  - url: https://api.your-middleware.com
    description: Main URL of the middleware
paths:
  /static/players:
    get:
      summary: Get all players
      responses:
        '200':
          description: A list of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /static/teams:
    get:
      summary: Get all teams
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
                example:
                  - id: 1
                    full_name: Atlanta Hawks
                    abbreviation: ATL
                    nickname: Hawks
                    city: Atlanta
                    state: Georgia
                    year_founded: 1949
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

  /storic/game/stats:
    get:
      summary: Get games statistics by date and teams
      parameters:
        - in: query
          name: fromDate
          schema:
            type: string
            format: date
          required: true
          description: The start date
        - in: query
          name: toDate
          schema:
            type: string
            format: date
          required: true
          description: The end date
        - in: query
          name: teamTicker1
          schema:
            type: string
          required: true
          description: The first team ticker
        - in: query
          name: teamTicker2
          schema:
            type: string
          required: true
          description: The second team ticker
      responses:
        '200':
          description: A list of GameInfo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameInfo'
        '400':
          description: Bad Request - The request parameters are invalid.
        '401':
          description: Unauthorized - API key is missing or invalid.
        '403':
          description: Forbidden - You do not have permission to access this resource.
        '500':
          description: Internal Server Error - An error occurred on the server.

# Team base stats and GameInfo stats make two endpoints:
#  - one with last N as parameter
#  - one with fromdate todate as parameters

components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The player ID
        full_name:
          type: string
          description: The player full name
        first_name:
          type: string
          description: The player first name
        last_name:
          type: string
          description: The player last name
        is_active:
          type: boolean
          description: The player is active
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The team ID
        full_name:
          type: string
          description: The team full name
        abbreviation:
          type: string
          description: The team abbreviation
        nickname:
          type: string
          description: The team nickname
        city:
          type: string
          description: The team city
        state:
          type: string
          description: The team state
        year_founded:
          type: integer
          format: int64
          description: The team year founded
    TeamBaseStats:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The team ID
        wins:
          type: integer
          format: int64
          description: The number of wins
        losses:
          type: integer
          format: int64
          description: The number of losses
        average_points:
          type: number
          format: float
          description: The average points per game
        average_points_against:
          type: number
          format: float
          description: The average points against per game
    GameInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The game ID
        date:
          type: string
          format: date
          description: The game date
        home_team_id:
          type: integer
          format: int64
          description: The home team ID
        away_team_id:
          type: integer
          format: int64
          description: The away team ID
        winner:
          type: string
          enum: [ home, away ]
          description: The winner team
        home_wins_until_game:
          type: integer
          format: int64
          description: The number of wins of the home team until this game
        home_losses_until_game:
          type: integer
          format: int64
          description: The number of losses of the home team until this game
        away_wins_until_game:
          type: integer
          format: int64
          description: The number of wins of the away team until this game
        away_losses_until_game:
          type: integer
          format: int64
          description: The number of losses of the away team until this game
        home_pts:
          type: integer
          format: int64
          description: The winner team points
        away_pts:
          type: integer
          format: int64
          description: The loser team points
        home_fgm:
          type: integer
          format: int64
          description: The home team field goals made
        home_fga:
          type: integer
          format: int64
          description: The home team field goals attempted
        home_fg3m:
          type: integer
          format: int64
          description: The home team three points made
        home_fg3a:
          type: integer
          format: int64
          description: The home team three points attempted
        home_ftm:
          type: integer
          format: int64
          description: The home team free throws made
        home_fta:
          type: integer
          format: int64
          description: The home team free throws attempted
        home_oreb:
          type: integer
          format: int64
          description: The home team offensive rebounds
        home_dreb:
          type: integer
          format: int64
          description: The home team defensive rebounds
        home_reb:
          type: integer
          format: int64
          description: The home team total rebounds
        home_ast:
          type: integer
          format: int64
          description: The home team assists
        home_stl:
          type: integer
          format: int64
          description: The home team steals
        home_blk:
          type: integer
          format: int64
          description: The home team blocks
        home_tov:
          type: integer
          format: int64
          description: The home team turnovers
        home_pf:
          type: integer
          format: int64
          description: The home team personal fouls


        away_fgm:
          type: integer
          format: int64
          description: The away team field goals made
        away_fga:
          type: integer
          format: int64
          description: The away team field goals attempted
        away_fg3m:
          type: integer
          format: int64
          description: The away team three points made
        away_fg3a:
          type: integer
          format: int64
          description: The away team three points attempted
        away_ftm:
          type: integer
          format: int64
          description: The away team free throws made
        away_fta:
          type: integer
          format: int64
          description: The away team free throws attempted
        away_oreb:
          type: integer
          format: int64
          description: The away team offensive rebounds
        away_dreb:
          type: integer
          format: int64
          description: The away team defensive rebounds
        away_reb:
          type: integer
          format: int64
          description: The away team total rebounds
        away_ast:
          type: integer
          format: int64
          description: The away team assists
        away_stl:
          type: integer
          format: int64
          description: The away team steals
        away_blk:
          type: integer
          format: int64
          description: The away team blocks
        away_tov:
          type: integer
          format: int64
          description: The away team turnovers
        away_pf:
          type: integer
          format: int64
          description: The away team personal fouls



