openapi: 3.0.1
info:
  title: NBA API
  description: API for retrieving NBA teams, matches, players, and their statistics
  version: 1.0.0
paths:
  /teams:
    get:
      summary: Retrieve all teams by ticker and season
      parameters:
        - in: query
          name: team_tickers
          schema:
            type: array
            items:
              type: string
          required: true
          description: List of team tickers
          example: ["BOS", "LAL", "MIA"]
        - in: query
          name: season
          schema:
            type: string
          required: true
          description: NBA season (e.g., 2023-24)
          example: "2023-24"
      responses:
        '200':
          description: A list of teams with their information and players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'

  /teams/{team_ticker}:
    get:
      summary: Retrieve team information and players by ticker and season
      parameters:
        - in: path
          name: team_ticker
          schema:
            type: string
          required: true
          description: Team ticker
          example: "BOS"
        - in: query
          name: season
          schema:
            type: string
          required: true
          description: NBA season (e.g., 2023-24)
          example: "2023-24"
      responses:
        '200':
          description: Team information and list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'

  /teams/{team_id}/stats:
    get:
      summary: Retrieve team stats by team ID, season, date, number of games, and location
      parameters:
        - in: path
          name: team_id
          schema:
            type: integer
          required: true
          description: Team ID
          example: 1610612738
        - in: query
          name: season
          schema:
            type: string
          required: true
          description: NBA season (e.g., 2023-24)
          example: "2023-24"
        - in: query
          name: date_to
          schema:
            type: string
            format: date
          required: true
          description: Match date up to consider for the stats (format:'YYYY-MM-DD')
          example: "2024-08-08"
        - in: query
          name: last_x
          schema:
            type: integer
          required: false
          description: Number of last games to consider
          example: 5
        - in: query
          name: home_away_filter
          schema:
            type: string
          required: false
          description: Location of the games (HOME or AWAY)
          example: "HOME"
      responses:
        '200':
          description: A list of team stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamStats'

  /matches:
    get:
      summary: Retrieve all matches beetween two dates
      parameters:
        - in: query
          name: date_from
          schema:
            type: string
          required: true
          description: The cutoff date from which games are considered (format:'YYYY-MM-DD')
          example: "2024-04-14"
        - in: query
          name: date_to
          schema:
            type: string
          required: false
          description: The cutoff date until which games are considered (format:'YYYY-MM-DD')
          example: "2024-04-14"
      responses:
        '200':
          description: A list of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'

  /match/{match_id}/stats:
    get:
      summary: Retrieve match stats by match ID
      parameters:
        - in: path
          name: match_id
          schema:
            type: string
          required: true
          description: Match ID
          example: "0022301187"
        - in: query
          name: match_date
          schema:
            type: string
          required: true
          description: The date of the match (format:'YYYY-MM-DD')
          example: "2024-04-14"
      responses:
        '200':
          description: Match stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchStats'

  /players/{player_id}/stats:
    get:
      summary: Retrieve player stats by player ID, season, date, location and number of games
      parameters:
        - in: path
          name: player_id
          schema:
            type: string
          required: true
          description: Player ID
          example: "1629027"
        - in: query
          name: season
          schema:
            type: string
          required: true
          description: NBA season (e.g., 2023-24)
          example: "2023-24"
        - in: query
          name: date_to
          schema:
            type: string
            format: date
          required: true
          description: Match date up to consider for the stats (format:'YYYY-MM-DD')
          example: "2024-08-08"
        - in: query
          name: last_x
          schema:
            type: integer
          required: false
          description: Number of last games to consider
          example: 5
        - in: query
          name: home_away_filter
          schema:
            type: string
          required: false
          description: Location of the games (HOME or AWAY)
          example: "HOME"
      responses:
        '200':
          description: Player stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerStats'

components:
  schemas:
    Team:
      type: object
      properties:
        team_ticker:
          type: string
          example: "BOS"
        team_info:
          $ref: '#/components/schemas/TeamInfo'
        team_players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    TeamInfo:
      type: object
      properties:
        id:
          type: integer
          example: 1610612738
        full_name:
          type: string
          example: "Boston Celtics"
        abbreviation:
          type: string
          example: "BOS"
        nickname:
          type: string
          example: "Celtics"
        city:
          type: string
          example: "Boston"
        state:
          type: string
          example: "MA"
        year_founded:
          type: integer
          example: 1946
        arena:
          type: string
          example: "TD Garden"

    Player:
      type: object
      properties:
        player_id:
          type: integer
          example: 1630552
        player:
          type: string
          example: "Marcus Smart"
        num:
          type: string
          example: "36"
        position:
          type: string
          example: "G"
        height:
          type: string
          example: "6-3"
        weight:
          type: integer
          example: 220
        age:
          type: number
          example: 29
        exp:
          type: string
          example: "6"

    TeamStats:
      type: object
      properties:
        all_stats:
          type: array
          items:
            $ref: '#/components/schemas/TeamMatchStat'
        totals:
          type: object
          items:
            properties:
              wins:
                type: integer
                example: 2
              losses:
                type: integer
                example: 3
        average:
          $ref: '#/components/schemas/Average'
       
       
    AveragePlayer:
      allOf:
        - $ref: '#/components/schemas/Average'
        - type: object
          properties:
            plus_minus:
                type: number
                example: -2.2
            
    Average:
          type: object
          items:
            properties:
              fgm:
                type: integer
                example: 40.4
              fga:
                type: integer
                example: 85.5
              fg_pct:
                type: number
                example: 0.4367
              fg3m:
                type: number
                example: 12.2
              fg3a:
                type: number
                example: 32.0
              fg3_pct:
                type: number
                example: 0.4367
              ftm:
                type: number
                example: 18.3
              fta:
                type: number
                example: 22.0
              ft_pct:
                type: number
                example: 0.4367
              oreb:
                type: number
                example: 10.1
              dreb:
                type: number
                example: 35.8
              reb:
                type: number
                example: 45.9
              ast:
                type: number
                example: 25
              stl:
                type: number
                example: 8.4
              blk:
                type: number
                example: 5.4
              tov:
                type: number
                example: 13.4
              pf:
                type: number
                example: 20.0
              pts:
                type: number
                example: 16.4

    Match:
      type: object
      properties:
        match_up:
          type: string
          example: "CLE vs. CHA"
        game_id:
          type: string
          example: "0022301187"
        date:
          type: string
          format: date
          example: "2024-04-14"
        home_team:
          $ref: '#/components/schemas/TeamInfo'
        away_team:
          $ref: '#/components/schemas/TeamInfo'
        referee:
          $ref: '#/components/schemas/Referee'
          
    Referee:
      type: object
      properties:
        name:
          type: string
          example: "Sean Corbin"
        id:
          type: integer
          example: 1151

    MatchStats:
      type: object
      properties:
        actual_match_stats:
          type: array
          items:
            $ref: '#/components/schemas/ActualMatchStats'
        last_match_stats:
          type: array
          items:
            $ref: '#/components/schemas/LastMatchStats'

    GlobalStats:
      type: object
      properties:
        game_id:
          type: string
          example: "0022301198"
        game_date:
          type: string
          format: date
          example: "2024-04-14"
        match_up:
          type: string
          example: "GSW vs. UTA"
        winner:
          type: string
          example: "GSW"
        home_point:
          type: integer
          example: 123
        away_point:
          type: integer
          example: 116

    ActualMatchStats:
      type: object
      properties:
        global_stats:
          $ref: '#/components/schemas/GlobalStats'
        by_home_stats:
          $ref: '#/components/schemas/Stat'
        by_away_stats:
          $ref: '#/components/schemas/Stat'

    LastMatchStats:
      type: object
      properties:
        global_stats:
          type: array
          items:
            $ref: '#/components/schemas/GlobalStats'
        by_home_stats:
          type: array
          items:
            $ref: '#/components/schemas/Stat'
        by_away_stats:
          type: array
          items:
            $ref: '#/components/schemas/Stat'
         
    TeamMatchStat:
      type: object
      properties:
        team_id:
          type: integer
          example: 1610612738
        team_abbreviation:
          type: string
          example: "BOS"
        team_name:
          type: string
          example: "Boston Celtics"
        game_id:
          type: string
          example: "0022001074"
        game_date:
          type: string
          format: date
          example: "2024-01-23"
        match_up:
          type: string
          example: "BOS vs. LAL"
        wl:
          type: string
          example: "W"
        w:
          type: integer
          example: 36
        l:
          type: integer
          example: 44
        w_pct:
          type: number
          example: 0.45
        min:
          type: integer
          example: 240
        fgm:
          type: integer
          example: 40
        fga:
          type: integer
          example: 85
        fg_pct:
          type: number
          example: 47.1
        fg3m:
          type: integer
          example: 12
        fg3a:
          type: integer
          example: 32
        fg3_pct:
          type: number
          example: 37.5
        ftm:
          type: integer
          example: 18
        fta:
          type: integer
          example: 22
        ft_pct:
          type: number
          example: 81.8
        oreb:
          type: integer
          example: 10
        dreb:
          type: integer
          example: 35
        reb:
          type: integer
          example: 45
        ast:
          type: integer
          example: 25
        stl:
          type: integer
          example: 8
        blk:
          type: integer
          example: 5
        tov:
          type: integer
          example: 13
        pf:
          type: integer
          example: 20
        pts:
          type: integer
          example: 110
          
    Stat:
      type: object
      properties:
        season_id:
          type: string
          example: "22023"
        team_id:
          type: integer
          example: 1610612738
        team_abbreviation:
          type: string
          example: "BOS"
        team_name:
          type: string
          example: "Boston Celtics"
        game_id:
          type: string
          example: "0022001074"
        game_date:
          type: string
          format: date
          example: "2024-01-23"
        match_up:
          type: string
          example: "BOS vs. LAL"
        wl:
          type: string
          example: "W"
        min:
          type: integer
          example: 240
        fgm:
          type: integer
          example: 40
        fga:
          type: integer
          example: 85
        fg_pct:
          type: number
          example: 47.1
        fg3m:
          type: integer
          example: 12
        fg3a:
          type: integer
          example: 32
        fg3_pct:
          type: number
          example: 37.5
        ftm:
          type: integer
          example: 18
        fta:
          type: integer
          example: 22
        ft_pct:
          type: number
          example: 81.8
        oreb:
          type: integer
          example: 10
        dreb:
          type: integer
          example: 35
        reb:
          type: integer
          example: 45
        ast:
          type: integer
          example: 25
        stl:
          type: integer
          example: 8
        blk:
          type: integer
          example: 5
        tov:
          type: integer
          example: 13
        pf:
          type: integer
          example: 20
        pts:
          type: integer
          example: 110
        plus_minus:
          type: number
          example: -6
        video_available:
          type: number
          example: 1

    PlayerStats:
      type: object
      properties:
        all_stats:
          type: array
          items:
            $ref: '#/components/schemas/PlayerMatchStats'
        totals:
          type: object
          items:
            properties:
              wins:
                type: integer
                example: 2
              losses:
                type: integer
                example: 3
        average:
          $ref: '#/components/schemas/AveragePlayer'
        player_efficiency:
          type: object
          items:
            properties:
              all:
                type: number
                example: 19.5192
              filtered_matches:
                type: number
                example: 14.6

    PlayerMatchStats:
      type: object
      properties:
        season_id:
          type: string
          example: "22023"
        player_id:
          type: integer
          example: 203507
        game_id:
          type: string
          example: "0022001074"
        game_date:
          type: string
          format: date
          example: "APR 10, 2024"
        match_up:
          type: string
          example: "BOS vs. LAL"
        wl:
          type: string
          example: "W"
        min:
          type: number
          example: 36
        fgm:
          type: number
          example: 8
        fga:
          type: number
          example: 15
        fg_pct:
          type: number
          example: 53.3
        fg3m:
          type: number
          example: 4
        fg3a:
          type: number
          example: 9
        fg3_pct:
          type: number
          example: 44.4
        ftm:
          type: number
          example: 2
        fta:
          type: number
          example: 2
        ft_pct:
          type: number
          example: 100
        oreb:
          type: number
          example: 1
        dreb:
          type: number
          example: 4
        reb:
          type: number
          example: 5
        ast:
          type: number
          example: 7
        stl:
          type: number
          example: 2
        blk:
          type: number
          example: 1
        tov:
          type: number
          example: 3
        pf:
          type: number
          example: 4
        pts:
          type: number
          example: 22
        plus_minus:
          type: number
          example: -6
        video_available:
          type: number
          example: 1
