name: Create and push nba_api docker image

on:
  push:
    branches: [ "webapp" ]
    paths:
      - 'nba_api/**'

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: nba_api/deployment/version

      - name: Read version
        id: repository
        uses: juliangruber/read-file-action@v1
        with:
          path: nba_api/deployment/repository

      - name: Update dockerfile
        run: ./deployment/update-dockerfile.sh
        working-directory: nba_api

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./nba_api
          file: ./nba_api/deployment/Dockerfile
          tags: |
            ${{ secrets.ACR_SERVER }}/${{ steps.repository.outputs.content }}/nba_api:${{ steps.version.outputs.content }}
            ${{ secrets.ACR_SERVER }}/${{ steps.repository.outputs.content }}/nba_api:latest


