name: Create and push nba_api docker image

on:
  push:
    branches: [ "master", "nba_api_rest_middleware" ]
    paths:
      - 'nba_api/**'

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: nba_api/deployment/version

      - name: Read port
        id: port
        uses: juliangruber/read-file-action@v1
        with:
          path: nba_api/deployment/port

      - name: Update dockerfile
        run: ./deployment/update-dockerfile.sh
        working-directory: nba_api

      - name: Echoing
        run: echo ${{ steps.version.outputs.content }} ${{ steps.port.outputs.content }}

#      - name: Build and push
#        uses: docker/build-push-action@v6
